services:
  - type: web
    name: spectral-lie-api
    env: python
    region: singapore # Optional, can accept defaults
    plan: free # Explicitly optimized for free tier
    
    buildCommand: |
      pip install -r part3_api/requirements.txt
      pip install -e part1_audio_features
      pip install -e part2_detection
    
    startCommand: cd part3_api && gunicorn -k uvicorn.workers.UvicornWorker -w 1 --preload app.main:app -b 0.0.0.0:10000
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: 1
      # Optimization for Low RAM
      - key: OMP_NUM_THREADS
        value: 1
      - key: MKL_NUM_THREADS
        value: 1
